# Generated by Django 4.2.1 on 2023-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('type', models.TextField(choices=[('IT', 'IT'), ('NON IT', 'NON IT'), ('COMPUTER', 'COMPUTER')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
